events {}

http {
    upstream boogle {
        server query1:8000;
        server query2:8000;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://boogle;
        }
    }
}

